---
title: "Exam"
author: "Qiyun Huang"
date: "10/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#import data
```{r, echo=FALSE, eval=FALSE}
library(tidyverse)
library(haven)
library(readr)
library(ggplot2)

BRFSS2017<-read_csv("https://raw.githubusercontent.com/kijohnson/ADA-Fall-2021/master/BRFSS2017_10percent_v.csv")  %>%
  na.omit()

#recode sex
BRFSS2017$SEX<-factor(BRFSS2017$SEX, 
                      levels = c(1, 2), 
                      labels = c("Male", "Female"))
table(BRFSS2017$SEX)
```

#calculate the median

```{r}
by(BRFSS2017$ht_meters, BRFSS2017$SEX, summary) # summary table of hight group by sex
```

```{r}
#created a new variable M that calculate median for hight
M = tapply(BRFSS2017$ht_meters,
           INDEX = BRFSS2017$SEX,
           FUN   = median)
#creat boxplot hight by sex
boxplot(ht_meters ~ SEX,
        data=BRFSS2017,
        ylab="ht_meters")
points(M,
       col="red",
       pch="+",
       cex=2) # add point where the median is



```

#Add code to determine the man height in females and males
```{r}
mean(BRFSS2017[which(BRFSS2017$SEX=='Male'),] $ht_meters)
mean(BRFSS2017[which(BRFSS2017$SEX=='Female'),] $ht_meters)
#Male [1] 1.781877
#female [1] 1.631247
```